@token= {{login.response.body.token}}

####################################
# Register user
####################################
POST http://127.0.0.1:3001/api/register
Content-Type: application/json

{
	"email": "admin@admin.com",
	"password": "pass",
	"username": "admin",
	"firstName": "Jan",
	"lastName": "Kowalski"
}

####################################
# Login user
####################################
# @name login
POST http://127.0.0.1:3001/api/login
Content-Type: application/json

{
	"email": "admin@admin.com",
	"password": "pass"
}

####################################
# Get user info
####################################
GET http://127.0.0.1:3001/api/user/1

####################################
# Get all user info
####################################
GET http://127.0.0.1:3001/api/user
Authorization: Bearer {{token}}

####################################
# Change Password
####################################
PUT http://127.0.0.1:3001/api/change-password
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"oldPassword": "password",
	"newPassword": "password2"
}

####################################
# Get all reviews
####################################
GET http://127.0.0.1:3001/api/reviews


####################################
# Create review
####################################
POST http://127.0.0.1:3001/api/reviews
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"userId": "2",
	"productId": "2",
	"rating": 5,
	"text": "I really like this product"
}