@token= {{login.response.body.token}}
@userId= {{login.response.body.id}}



####################################
# Register user
####################################
POST http://127.0.0.1:3001/api/register
Content-Type: application/json

{
	"email": "admin@corporation.com",
	"password": "password"
}

####################################
# Login user
####################################
# @name login
POST http://127.0.0.1:3001/api/login
Content-Type: application/json

{
	"email": "admin@corporation.com",
	"password": "password"
}
